import styles from "../../styles/Terms&Conditions/Terms&Conditions.module.scss";

export default function TermsConditions() {
  return (
    <section className={styles["pageWrapper"]}>
      <h1 className={styles["pageTitle"]}>Terms & Conditions</h1>
      <div className={styles["contentWrapper"]}>
        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>
            Agreement between User and Navneet Education Ltd.
            <br />
            (“Terms of Use”)
          </h2>
          <p>
            Welcome to Navneet.com. Your access to or use of Navneet.com website
            and/or any sub domains thereof, including the entire website (the
            “Website”), its Content and Services (as defined below), constitutes
            your acceptance and agreement to be bound by the following terms and
            conditions. Please read this document carefully. If you have any
            questions regarding the Terms of Use, please contact us.
          </p>
        </div>
        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>1. Definitions</h2>
          <p>Navneet, “we”, “us”, “our”: Navneet Education Ltd..</p>
          <p>
            User, “you”, “yours”: anyone who accesses the Website and/or uses
            the Content and/or Services (as defined below)
          </p>
          <p>
            Products: all and any products provided by Navneet on the Website,
            including, but not limited to, Navatar Personality Test, Navatar
            Contest Engine
          </p>
          <p>
            Content: all and any content contained on or generated by the
            Website, including, without limitation, Products, questionnaires,
            reports, text, graphics, and software.
          </p>
          <p>
            Services: all and any services provided by Navneet from the Website,
            including, but not limited to, your access to the Content or
            portions there of, your account and other features.
          </p>
        </div>
        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>2. Prohibited Use</h2>
          <p>
            You may not use the Website, its Content and/or Services for any
            illegal purpose or in any way prohibited by with these Terms of Use.
            Your use of the Website, its Content and/or Services is subject to
            all applicable international, federal, provincial, state and local
            laws and regulations. You may not use the Website, its Content
            and/or Services in any manner which could damage, disable,
            overburden, or impair the Website, its Content and/or Services or
            interfere with any other party’s use and enjoyment of Website, its
            Content and/or Services.{" "}
          </p>
          <p>
            You may not obtain or attempt to obtain any materials or information
            through any means not intentionally made available or provided
            through the Website.
          </p>
        </div>
        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>3. Liability Disclaimer</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE WEBSITE,
            CONTENT AND SERVICES ARE PROVIDED “AS IS” WITHOUT WARRANTY OR
            CONDITION OF ANY KIND. Navneet Education Ltd. AND/OR ITS OWNERS,
            DIRECTORS, PARTNERS, ASSOCIATES AND SUPPLIERS HEREBY DISCLAIM ALL
            WARRANTIES AND CONDITIONS WITH REGARD TO THE WEBSITE, CONTENT AND
            SERVICES, INCLUDING ALL IMPLIED WARRANTIES OR CONDITIONS OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE,
            NON-INFRINGEMENT, SECURITY AND AVAILABILITY.
          </p>
          <p>
            THE CONTENT, PRODUCTS AND SERVICES, OR ANY INFORMATION INCLUDED IN
            OR AVAILABLE THROUGH THE WEBSITE MAY INCLUDE INACCURACIES, ERRORS,
            OR BE INCOMPLETE. ADVICE RECEIVED VIA Navneet Education Ltd.
            WEBSITE, CONTENT AND/OR SERVICES MUST NOT BE RELIED UPON FOR
            PERSONAL, MEDICAL, LEGAL OR FINANCIAL DECISIONS AND YOU SHOULD
            CONSULT AN APPROPRIATE PROFESSIONAL FOR SPECIFIC ADVICE FOR YOUR
            SITUATION. WEBSITE, CONTENT AND SERVICES ARE INTENDED TO BE USED FOR
            NON-HEALTH AND NON-LIFE THREATENING SITUATIONS ONLY.
          </p>
          <p>
            Navneet MAKES NO WARRANTY THAT THE CONTENT AND/OR SERVICES ARE
            SUITABLE FOR ANY PARTICULAR PURPOSE INCLUDING PERSONALITY
            ASSESSMENT, MATCHING, COUNSELLING, PRE-EMPLOYMENT SCREENING,
            PREDICTING BEHAVIOURS, ABILITIES AND SKILLS.
          </p>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL
            Navneet Education Ltd. AND/OR OWNERS, DIRECTORS, PARTNERS AND
            SUPPLIERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL,
            SPECIAL, CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER INCLUDING,
            WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS,
            ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR PERFORMANCE
            OF THE WEBSITE, CONTENT AND/OR SERVICES, WITH THE DELAY OR INABILITY
            TO USE THE WEBSITE, CONTENT AND/OR SERVICES, WITH PROVISION OR
            FAILURE TO DELIVER THE WEBSITE, CONTENT AND/OR SERVICES, FOR BREACH
            OF INFORMATION, INCLUDING, WITHOUT LIMITATION, PERSONAL INFORMATION
            YOU PROVIDED TO Navneet Education Ltd., OR SUBMITTED VIA THE
            WEBSITE, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT
            LIABILITY OR OTHERWISE, EVEN IF Navneet Education Ltd. HAS BEEN
            ADVISED OF THE POSSIBILITY OF DAMAGES.
          </p>
          <p>
            IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE WEBSITE AND/OR
            CONTENT AND/OR SERVICES, OR WITH ANY OF THESE TERMS OF USE, YOUR
            SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE WEBSITE,
            CONTENT AND SERVICES.
          </p>
          <p>
            IN NO EVENT WILL TOTAL LIABILITY OF Navneet Education Ltd. UNDER OR
            RELATED TO THESE TERMS OF USE, THE TERMINATION THEREOF, AND/OR THE
            PROVISION OF THE WEBSITE AND/OR CONTENT AND/OR SERVICE, REGARDLESS
            OF THE FORM OF ACTION, EXCEED THE FEES WE ACTUALLY RECEIVED FROM YOU
            DURING THE ONE (1) YEAR PERIOD PRECEEDING THE INCIDENT GIVING RISE
            TO SUCH LIABILITY.{" "}
          </p>
        </div>
        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>4. Restrictions</h2>
          <p>
            The Navatar test including their questionnaires and results, are
            provided free of charge only for personal non-commercial use or
            educational purposes. Any other use of Navatar test including any
            indirect commercial use such as, without limitation, instructing
            prospective job candidates to take Navatar test and provide results
            to the hiring organization or a recruitment agency as part of their
            recruitment process, is strictly prohibited unless agreed to in
            writing by Navneet. You may submit your permission inquiry to us
            here.{" "}
          </p>
        </div>
        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>5. Termination</h2>
          <p>
            You may terminate the Terms of Use at any time and effective
            immediately by discontinuing all use of the Website, Content and
            Services and destroying all materials you obtained from or via the
            Website, and any copies thereof.{" "}
          </p>
          <p>
            Navneet Education Ltd. may terminate these Terms of Use with or
            without cause at any time and effective immediately. Upon receive a
            notice of termination from Navneet Education Ltd. , you must destroy
            all materials obtained from the Website and via the Services and any
            copies thereof.
          </p>
          <p>
            Sections 1,2,3,6,8,9,10,11,12,13,14,15 and all other provisions of
            these Terms of Use which may reasonably be construed as surviving
            termination hereof, shall survive termination of these Terms of Use
            for any reason.
          </p>
        </div>
        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>6. Access Restriction</h2>
          <p>
            Navneet Education Ltd. may terminate or restrict your access to all
            and any part of the Website, Products and/or Services at any time,
            in its sole and absolute discretion, and effective immediately.{" "}
          </p>
        </div>
        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>7. Third Party Services</h2>
          <p>
            Navneet Education Ltd. may refer, advertise, and/or offer for sale,
            via its Website, Content or Services, certain third party services
            and/or products (“Third Party Services”), including, without
            limitation, links to other websites (“Linked Sites”), or
            advertisement banners presented by third parties (“Ads”) that help
            us keep providing certain content and services free of charge.
            Navneet Education Ltd. has no control over the Third Party Services
            and over visitor’s interaction with them. Terms of use and
            information practices of these third parties are not covered by our
            policies. Navneet Education ltd. is not responsible for the content
            of any Linked Site or information presented on any third party Ad
            included on our Website. The inclusion of any link or Ad does not
            imply endorsement by Navneet Education Ltd. of any the Linked Sites
            or Ads, or any association with the operators of any of the Linked
            Sites.{" "}
          </p>
          <p>
            Navneet Education Ltd. makes no warranties or representations
            whatsoever, express or implied, with regard to any Third Party
            Services, Linked Sites, and/or Ads. You will not consider Navneet
            Education ltd. , nor will Navneet Education ltd. be construed, as a
            party to any transactions relating to Third Party Services, Linked
            Sites, and/or Ads, whether or not Navneet Education Ltd. may have
            received some form of revenue or other remuneration in connection
            with the transaction, nor shall Navneet be liable for any costs or
            damages arising out of or relating to, either directly or
            indirectly, the Third Party Services, Linked Sites, and/or Ads.
          </p>
        </div>

        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>
            8. Modifications of These Terms of Use
          </h2>
          <p>
            Navneet Education ltd. reserves the right, to make changes to these
            Terms of Use from time to time, in its sole discretion. The updated
            Terms of Use are available to the User via the Website. You are
            advised to check the Terms of Use before using Content and/or
            Services to determine whether any changes have been made thereto. If
            you do not agree to any changes in the Terms of Use, please
            terminate these Terms of Use by immediately by (a) notifying Navneet
            Education ltd. that you are unwilling to accept the changes to the
            Terms of Use, and (b) by discontinuing your access to and use of
            Website, its Content and Services. Your continued access to and/or
            use of the Website, Content and/or Services constitutes your
            acceptance of these Terms of Use and any changes thereto.{" "}
          </p>
        </div>

        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>
            9. Modifications of Content and Services
          </h2>
          <p>
            Navneet Education ltd. reserves the right, in its sole discretion,
            to make changes to or discontinue Content and/or Services, or
            portions thereof, including, without limitation, changing pricing of
            Products and Services, with or without notice to you, and without
            liability to you or any third party.{" "}
          </p>
        </div>

        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>10. Applicable Law</h2>
          <p>
            To the maximum extent permitted by law, this agreement is governed
            by the laws of the State of California and you hereby consent to the
            exclusive jurisdiction and venue of courts in San Francisco,
            California, in all disputes arising out of or relating to the use of
            the Web Site, Content and/or Services. Use of the Website, Content
            and/or Services is unauthorized in any jurisdiction that does not
            give effect to all provisions of these terms and conditions,
            including without limitation this paragraph. You agree that no joint
            venture, partnership, employment, or agency relationship exists
            between you and Navneet as a result of this agreement or use of the
            Website, Content and/or Services. Navneet Education ltd. performance
            of this agreement is subject to existing laws and legal process, and
            nothing contained in this agreement is in derogation of Navneet
            Education ltd. right to comply with governmental, court and law
            enforcement requests or requirements relating to your use of the
            Website, Content and/or Services or information provided to or
            gathered by Navneet with respect to such use. If any part of this
            agreement is determined to be invalid or unenforceable pursuant to
            applicable law including, but not limited to, the warranty
            disclaimers and liability limitations set forth above, then the
            invalid or unenforceable provision will be deemed superseded by a
            valid, enforceable provision that most closely matches the intent of
            the original provision and the remainder of the agreement shall
            continue in effect. Unless otherwise specified herein, this
            agreement constitutes the entire agreement between the user and
            Navneet Education ltd. with respect to the Website, Content and/or
            Services and it supersedes all prior or contemporaneous
            communications and proposals, whether electronic, oral or written,
            between the user and Navneet Education ltd. with respect to the
            Website, Content and/or Services. A printed version of this
            agreement and of any notice given in electronic form shall be
            admissible in judicial or administrative proceedings based upon or
            relating to this agreement to the same extent an d subject to the
            same conditions as other business documents and records originally
            generated and maintained in printed form. It is the express wish
            that this agreement and all related documents be drawn up in
            English.{" "}
          </p>
        </div>

        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>
            11. Intellectual Property Ownership, Copyright, Reservation of
            Rights
          </h2>
          <p>
            a) Navatar test and the software of these tests, and all Content of
            the Website are Copyright © Navneet Education ltd. or its licensors.
            All Rights Reserved.
          </p>
          <p>
            b) All of the intellectual property rights in the Website and
            Content belong to Navneet Education ltd. or its licensors. The
            Products, their scoring algorithms, their report generation
            algorithms, and their software code are valuable intellectually
            property (trade secrets and confidential information) of Navneet
            Education ltd. You have no intellectual property rights in the
            Content, the Products, the Website and any materials thereon.
          </p>
          <p>
            c) All Content is protected by law, including without limitation the
            copyright laws of the India, Mumbai and other countries, and by
            international treaty provisions. All rights not expressly granted
            are reserved by Navneet Education ltd. and its licensors.
          </p>
          <p>
            d) The unauthorized use of the Content will result in civil and
            criminal sanctions, including intellectual property proceedings, the
            pursuit of statutory damages, and all other recourse available to
            Navneet Education ltd.{" "}
          </p>
        </div>

        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>
            12. No reverse engineering, modification, website automation or
            integration
          </h2>
          <p>
            a) You shall not reverse engineer, decompile, disassemble,
            approximate, or otherwise attempt to discover the source code, the
            scoring algorithms, or the reports generation algorithm of Navneet
            Education ltd. website Products, or any of the Content.
          </p>
          <p>
            b) You shall not modify, adapt, translate, or create derivative
            works based upon the Website, Content, and any materials provided on
            or as a part of Website or Content. You shall not alter or remove
            any copyright or other proprietary notice that appears on the
            content provided on or as a part of Website, Content and/or
            Services.
          </p>
          <p>
            c) You shall not embed, integrate, automate usage of, Products
            offered on Navneet Education ltd. website, fully or partially,
            unless expressly permitted by Navneet Education ltd. in writing.{" "}
          </p>
        </div>

        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>13. Trademarks</h2>
          <p>
            All brand names, product names and titles used on this site are
            trademarks or trade names of their respective holders.
          </p>
          <p>
            Navneet Education ltd. Navatar test are trademarks or registered
            trademarks of Navneet Education ltd. or its licensors, in the India,
            Mumbai and other countries.
          </p>
          <p>
            Navneet Education ltd. Products use methodology, questionnaire,
            scoring and software that are proprietary to Navneet Education ltd.
          </p>
          <p>
            No permission is given in respect of the use of any of the above and
            any brand names, product names and titles used on this site. Any
            such use may constitute an infringement of the holders’ rights by
            you.{" "}
          </p>
        </div>
        <div className={styles["section"]}>
          <h2 className={styles["sectionHeading"]}>14. Indemnification</h2>
          <p>
            You agree to defend, indemnify and hold each of Navneet Education
            ltd. its subsidiaries, affiliates, officers, directors, shareholders
            and employees, harmless from any and all claims, demands,
            liabilities, losses, damages and/or expenses, including reasonable
            attorneys’ and expert witness fees, arising out of or relating to
            the use of the Website, Content and/or Services, and/or violation of
            these Terms of Use by you and/or any users of your account on the
            Website, including, without limitation, any breach of the
            representations and warranties made by you herein, any and all
            claims arising from the infringement by you, or any other user of
            your account, of any Proprietary Rights or other rights of any
            person or entity.{" "}
          </p>
        </div>
      </div>
    </section>
  );
}